Correct how to determine if pr required

diff --git a/.github/workflows/post-prod-sync-main.yaml b/.github/workflows/post-prod-sync-main.yaml
--- a/.github/workflows/post-prod-sync-main.yaml
+++ b/.github/workflows/post-prod-sync-main.yaml
@@ -13,13 +13,9 @@ jobs:
       - uses: actions/checkout@v2
         with:
           fetch-depth: 0
-      - name: Print is PR required?
-        run: git diff origin/main
       - name: Is PR required?
         id: pr_required
-        run: echo "::set-output name=pr_required::1"
-      - name: Print outputs
-        run: echo ${{ steps.pr_required.outputs.pr_required}}
+        run: echo "::set-output name=pr_required::$(git diff origin/main --quiet || echo 1)"
       - name: Extract branch name
         if: ${{ steps.pr_required.outputs.pr_required == 1}}
         shell: bash
